// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

 /**
  * Creating a sidebar enables you to:
  * - create an ordered group of docs
  * - render a sidebar for each doc of that group
  * - provide next/previous navigation
  *
  * The sidebars can be generated from the filesystem, or explicitly defined here.
  *
  * Create as many sidebars as you want.
  *
  * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
  */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' }, // auto-generate from docs folder
    {
      type: 'doc',
      id: 'juice-shop', // file name without .md
      label: 'Juice Shop Documentation', // menu label
    },
  ],
juiceShopSidebar: [
    {
      type: 'category',
      label: 'Juice Shop Master',
      items: [
        'juice-shop-master/README',
        'juice-shop-master/CHECKLIST',
        'challenges/xss/index-xss',
        'challenges/captcha/index-captcha',
        'challenges/admin/index-admin',
      ],
    },
 ],
};

export default sidebars;
